[Common]

# Диапазон страниц
page_range=1-

# Время, сколько секунд назад было опубликовано объявление.
# Для того, чтобы не применять этот фильтр оставляем поле пустым
time_sec=120

# Город или область
region=

# Районы через запятую
district=

# Станции метро через запятую
metro=

# Сколько идти от метро пешком
foot_mins=

# Тип сделки. Выбрать одно значение из:
# Купить: sale, снять: rent, посуточно: rentd
deal_type=sale

# Выбрать одно из значений. Квартира: flat, дом: suburban, офис: office
# Далее настройка будет зависеть от выбранного значения. Для каждого значения
# своя секция [Flat], [Suburban] или [Office]
offer_type=flat


[Flat]
# Квартиры

# Команата (поставить 1 или оставить поле пустым)
room=

# 1-комнатная кваритра (поставить 1 или оставить поле пустым)
rooms_1=

# 2-комнатная кваритра (поставить 1 или оставить поле пустым)
rooms_2=

# 3-комнатная кваритра (поставить 1 или оставить поле пустым)
rooms_3=

# 4-комнатная кваритра (поставить 1 или оставить поле пустым)
rooms_4=

# 5-комнатная кваритра (поставить 1 или оставить поле пустым)
rooms_5=

# 6-комнатная кваритра (поставить 1 или оставить поле пустым)
rooms_6=

# Студия (поставить 1 или оставить поле пустым)
studio=

# Свободная планировка (поставить 1 или оставить поле пустым)
free_plan=


[Suburban]
# Дом (поставить 1 или оставить поле пустым)
house=

# Часть дома (поставить 1 или оставить поле пустым)
house_part=

# Участок (поставить 1 или оставить поле пустым)
area=

# Таунхаус (поставить 1 или оставить поле пустым)
townhouse= 

# 0 - все, 1 - дом от застройщика, 2 - от собственника или агента
suburban_offer_filter=0



[Office]

# Офис (поставить 1 или оставить поле пустым)
office=

# Торговая площадь (поставить 1 или оставить поле пустым)
trade_area=

# Склад (поставить 1 или оставить поле пустым)
depot=

# Общепит (поставить 1 или оставить поле пустым)
public_catering=

# помещение свободного назначения (поставить 1 или оставить поле пустым)
free_zone=

# Гараж (поставить 1 или оставить поле пустым)
garage=

# Производство (поставить 1 или оставить поле пустым)
manufacture=

# Автосервис (поставить 1 или оставить поле пустым)
car_service=

# Готовый бизнес (поставить 1 или оставить поле пустым)
busines=

# Здание (поставить 1 или оставить поле пустым)
building=

# Бытовые услуги (поставить 1 или оставить поле пустым)
domestic_services=

# Коммерческая земля, если установлено в 1 то отменяет все предыдущие настройки в секции [Office]
commercial_land_sale=



[Output]
text=1
json=0
sqlite=0
xls=0
postgresql=0
rest_api_json=0

[TextFile]
file=out/cian-result.txt

[JSONFile]
file=

[SQLite]
file=

[XLS]
file=

[PostgreSQL]
url=

[RestApiJson]
url=




































