[Common]
host=spb.hh.ru
# robot, choose one of: Vacancies, Companies
robot=Companies
threads=100

[Companies]
area=
key_phrase=торговля
page_range=1-100
info_html=false
id_ranges=1-100
read_image=true

[Vacancies]
only_with_salary=false
salary=
areas=
info_html=false
key_phrase=Java
page_range=1-100
id_ranges=

# Outputs:

[TextFile]
enabled=true
vacancies_file=out2/vacancies.txt
companies_file=out2/companies.txt
backup_files=false

[JSONFile]
enabled=true
vacancies_file=out2/vacancies.json
companies_file=out2/companies.json
backup_files=false
indentation=true

[XLSFile]
enabled=true
vacancies_file=out2/vacancies.xls
companies_file=out2/companies.xls
backup_files=false
rows_per_sheet=100

[SQLite]
enabled=false
sqlite_file=out2/hh.db

[PostgreSQL]
enabled=false
url=
dbname=
username=
password=
